projects:
  database:
    schemaPath: server/src/database/generated/prisma.graphql
    extensions:
      prisma: server/src/database/prisma.yml
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: server/src/database/generated/prisma.ts
